language: java
sudo: false
cache:
    directories:
        - $HOME/.m2
env:
    global:
        - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g"
        - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g"
jdk:
    - oraclejdk8
services:
    - mongodb
